from flask import Flask, render_template, redirect, request, url_for

import numpy as np
from tensorflow import keras

app = Flask(__name__)

class_names = ['basket\n',
 'bulldozer\n',
 'ear\n',
 'telephone\n',
 'crab\n',
 'garden\n',
 'microphone\n',
 'cup\n',
 'house_plant\n',
 'pond\n',
 'flower\n',
 'school_bus\n',
 'face\n',
 'guitar\n',
 'bathtub\n',
 'diamond\n',
 'river\n',
 'string_bean\n',
 'pillow\n',
 'steak\n',
 'hot_air_balloon\n',
 'swing_set\n',
 'drums\n',
 'snowflake\n',
 'broom\n',
 'house\n',
 'headphones\n',
 'roller_coaster\n',
 'broccoli\n',
 'eyeglasses\n',
 'leg\n',
 'clarinet\n',
 'arm\n',
 'sink\n',
 'calculator\n',
 'calendar\n',
 'cruise_ship\n',
 'hurricane\n',
 'nail\n',
 'stop_sign\n',
 'pool\n',
 'stethoscope\n',
 'laptop\n',
 'carrot\n',
 'hot_tub\n',
 'keyboard\n',
 'moustache\n',
 'panda\n',
 'paintbrush\n',
 'foot\n',
 'hexagon\n',
 'police_car\n',
 'bush\n',
 'goatee\n',
 'marker\n',
 'sun\n',
 'campfire\n',
 'baseball_bat\n',
 'ceiling_fan\n',
 'pizza\n',
 'cooler\n',
 'fork\n',
 'compass\n',
 'frog\n',
 'lighthouse\n',
 'saw\n',
 'television\n',
 'coffee_cup\n',
 'feather\n',
 'octagon\n',
 'circle\n',
 'skyscraper\n',
 'map\n',
 'cello\n',
 'octopus\n',
 'ice_cream\n',
 'axe\n',
 'motorbike\n',
 'bowtie\n',
 'owl\n',
 'grass\n',
 'rainbow\n',
 'crayon\n',
 'remote_control\n',
 'stitches\n',
 'squiggle\n',
 'submarine\n',
 'bracelet\n',
 'dog\n',
 'sword\n',
 'leaf\n',
 'sandwich\n',
 'speedboat\n',
 'squirrel\n',
 'line\n',
 'firetruck\n',
 'sweater\n',
 'ocean\n',
 'candle\n',
 'fan\n',
 'pickup_truck\n',
 'sea_turtle\n',
 'snowman\n',
 'belt\n',
 'tennis_racquet\n',
 'asparagus\n',
 'onion\n',
 'envelope\n',
 'camel\n',
 'skateboard\n',
 'cloud\n',
 'mug\n',
 'dragon\n',
 'backpack\n',
 'rabbit\n',
 'nose\n',
 'matches\n',
 'horse\n',
 'piano\n',
 'palm_tree\n',
 'lobster\n',
 'computer\n',
 'spider\n',
 'drill\n',
 'blueberry\n',
 'bird\n',
 'finger\n',
 'elephant\n',
 'church\n',
 'couch\n',
 'paper_clip\n',
 'shoe\n',
 'jacket\n',
 'postcard\n',
 'lion\n',
 'bridge\n',
 'alarm_clock\n',
 'cake\n',
 'mouse\n',
 'necklace\n',
 'mermaid\n',
 'rhinoceros\n',
 'power_outlet\n',
 'pear\n',
 'helicopter\n',
 'bucket\n',
 'stove\n',
 'soccer_ball\n',
 'key\n',
 'sleeping_bag\n',
 'book\n',
 'saxophone\n',
 'elbow\n',
 'parrot\n',
 'anvil\n',
 'butterfly\n',
 'streetlight\n',
 'syringe\n',
 'sheep\n',
 'apple\n',
 'mouth\n',
 'raccoon\n',
 'lantern\n',
 'rake\n',
 'tent\n',
 'megaphone\n',
 'potato\n',
 'hourglass\n',
 'teddy-bear\n',
 'The_Eiffel_Tower\n',
 'barn\n',
 'eraser\n',
 'pig\n',
 'bench\n',
 'lollipop\n',
 'star\n',
 'ant\n',
 'fence\n',
 'dresser\n',
 'knee\n',
 'lipstick\n',
 'flamingo\n',
 'parachute\n',
 'The_Great_Wall_of_China\n',
 'castle\n',
 'birthday_cake\n',
 'duck\n',
 'snake\n',
 'spreadsheet\n',
 'peanut\n',
 'bed\n',
 'angel\n',
 'donut\n',
 'flashlight\n',
 'cat\n',
 'stairs\n',
 'lightning\n',
 'scissors\n',
 'screwdriver\n',
 'hat\n',
 'boomerang\n',
 'brain\n',
 'frying_pan\n',
 'mailbox\n',
 'peas\n',
 'see_saw\n',
 'mushroom\n',
 'dumbbell\n',
 'swan\n',
 'pants\n',
 'eye\n',
 'camera\n',
 'shorts\n',
 'bicycle\n',
 'square\n',
 'basketball\n',
 'hand\n',
 'scorpion\n',
 'monkey\n',
 'flying_saucer\n',
 'microwave\n',
 'helmet\n',
 'dishwasher\n',
 'paint_can\n',
 'oven\n',
 'crocodile\n',
 'pineapple\n',
 'diving_board\n',
 'hockey_puck\n',
 'chair\n',
 'camouflage\n',
 'golf_club\n',
 'passport\n',
 'cannon\n',
 'beach\n',
 'dolphin\n',
 'canoe\n',
 'giraffe\n',
 'bear\n',
 'spoon\n',
 'chandelier\n',
 'suitcase\n',
 'hamburger\n',
 'strawberry\n',
 'bread\n',
 'aircraft_carrier\n',
 'grapes\n',
 'rollerskates\n',
 'rain\n',
 'lighter\n',
 'floor_lamp\n',
 'ladder\n',
 'hot_dog\n',
 'hospital\n',
 'animal_migration\n',
 'hockey_stick\n',
 'hedgehog\n',
 'beard\n',
 'banana\n',
 'hammer\n',
 'bandage\n',
 'skull\n',
 'fish\n',
 'bat\n',
 'pliers\n',
 'clock\n',
 'sock\n',
 'bottlecap\n',
 'sailboat\n',
 'penguin\n',
 'mountain\n',
 'cookie\n',
 'knife\n',
 'fireplace\n',
 'table\n',
 'bus\n',
 'car\n',
 'snorkel\n',
 'door\n',
 'airplane\n',
 'smiley_face\n',
 'radio\n',
 'stereo\n',
 'cactus\n',
 'jail\n',
 'blackberry\n',
 'teapot\n',
 'cell_phone\n',
 'binoculars\n',
 'harp\n',
 'shark\n',
 'pencil\n',
 'picture_frame\n',
 'kangaroo\n',
 'ambulance\n',
 'purse\n',
 'flip_flops\n',
 'light_bulb\n',
 'baseball\n',
 'rifle\n',
 'popsicle\n',
 'bee\n',
 'moon\n',
 'shovel\n',
 'fire_hydrant\n',
 'garden_hose\n',
 'snail\n',
 'crown\n',
 'cow\n',
 'mosquito\n']


@app.route('/')
def Home():
    return render_template("home.html")

def normalize(data):
    "Takes a list or a list of lists and returns its normalized form"

    return np.interp(data, [0, 255], [0, 1])

@app.route('/draw', methods=['GET', 'POST'])
def draw():

    latex = []

    if request.method == 'POST':
        pixels = request.form['pixels']
        pixels = pixels.split(',')
        pixels = normalize(pixels)
        img = np.array(pixels).astype(float).reshape(28,28)

        model = keras.models.load_model('quickDraw84.model')
        pred = model.predict(np.expand_dims(img, axis=0))[0]
        ind = (-pred).argsort()[:7]
        latex = [class_names[x] for x in ind]

    return render_template("draw.html", pred=latex)


if __name__ == '__main__':
    app.run(debug=True)
